### ISSUE TITLE
Comparison algorithm

### ISSUE THREAD

**Issue by Max-Well-Wang** [gorkemcanates/Dual-Cross-Attention#3]
Why not compare with UCtransNet, or with the latest 2022 algorithm?

**Comment by gorkemcanates** [comment]
The model size and complexity of Uctransnet are significantly higher than our models so it wouldn't be a fair comparison. Our aim here is to improve Unet and its variants at a slight parameter and complexity increase rather than building an end-to-end model like Transunet, Uctransnet, Swinunet etc.
